@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Checkout Sequence, Logged-In User

actor "User" as user
participant "Frontend" as fe
participant "Backend" as be
participant "Stripe" as stripe
database "PostgreSQL" as db

user -> fe: Clicks "Go to checkout"
fe -> be: GET /api/v1/payment
be -> stripe: Create session and POST /v1/checkout/sessions
be <-- stripe: Return client_secret
be --> fe: Return client_secret
fe -> stripe: Embed Stripe's payment page using client_secret
fe <-- stripe: Redirect /orders?sessionId={CHECKOUT_SESSION_ID}
fe -> be: GET /api/v1/payment/order?sessionId={CHECKOUT_SESSION_ID}
be -> stripe: GET /v1/checkout/sessions/CHECKOUT_SESSION_ID
be <-- stripe: Session object
alt <font color=green>Order[userId, sessionId] not created yet</font>
    be -> db: Create Order
    be -> db: Delete Cart
    user <-- be: Send email (successful order)
end

be <-- stripe: POST /v1/stripe/webhook
alt <font color=green>"checkout.session.completed"</font>
    alt <font color=green>Order[userId, sessionId] not created yet</font>
        be -> db: Create Order
        be -> db: Delete Cart
        user <-- be: Send email (successful order)
    end
else <font color=red>"checkout.session.expired"</font>
    be -> be: Add log entry
end
@enduml